[server]
host = "0.0.0.0"
port = 8000


[llm]
provider = "gemini" # or "openai"
model = "gemini-1.5-flash"
api_key = "YOUR_GEMINI_API_KEY" # or set via LLM_API_KEY env var


[retrieval]
backend = "qdrant" # or "vertex"
qdrant_url = "https://YOUR-QDRANT-URL" # or set via QDRANT_URL env var
qdrant_api_key = "YOUR_QDRANT_KEY" # or set via QDRANT_API_KEY env var
collection = "trialwhisperer"


[data]
raw_dir = ".data/raw"
proc_dir = ".data/processed"


[data.api]
page_size = 100
max_studies = 200


[data.api.params]
"query.term" = "glioblastoma"
"filter.overallStatus" = ["Recruiting", "Active, not recruiting"]
"filter.studyType" = ["Interventional"]
"filter.phase" = ["Phase 2", "Phase 3"]
