# Example application defaults for TrialWhisperer.
#
# Copy to config/appsettings.toml to provide non-secret fallback values that
# complement the environment variables defined in config/.env. Secrets such as
# API keys and managed service URLs should live in the environment.

[server]
host = "0.0.0.0"
port = 8000

[llm]
provider = "gemini"
model = "gemini-2.5-flash"

[retrieval]
backend = "qdrant"
collection = "trialwhisperer"
qdrant_url = "http://localhost:6333"

[data]
raw_dir = ".data/raw"
proc_dir = ".data/processed"

[data.api]
backend = "requests"
page_size = 100
max_studies = 200
user_agent = "TrialWhisperer/ingest (+https://trialwhisperer.ai/contact)"

[data.api.params]
"query.term" = "glioblastoma"
"filter.overallStatus" = ["RECRUITING", "ACTIVE_NOT_RECRUITING"]
