[server]
host = "0.0.0.0"
port = 8000


[llm]
provider = "gemini" # or "openai"
model = "gemini-1.5-flash"
api_key = "YOUR_GEMINI_API_KEY" # or set via LLM_API_KEY env var


[retrieval]
backend = "qdrant" # or "vertex"
qdrant_url = "https://YOUR-QDRANT-URL" # or set via QDRANT_URL env var
qdrant_api_key = "YOUR_QDRANT_KEY" # or set via QDRANT_API_KEY env var
collection = "trialwhisperer"


[data]
raw_dir = ".data/raw"
proc_dir = ".data/processed"


[data.api]
# ClinicalTrials.gov API base URL (defaults to https://clinicaltrials.gov/api/v2)
page_size = 100
max_studies = 200


[data.api.params]
"query.term" = "glioblastoma"
"filter.overallStatus" = ["RECRUITING", "ACTIVE_NOT_RECRUITING"]
#"filter.studyType" = ["INTERVENTIONAL"]
#"filter.phase" = ["PHASE_2", "PHASE_3"]

