[server]
host = "0.0.0.0"
port = 8000


[llm]
provider = "gemini" # or "openai"
model = "gemini-2.5-flash"
api_key = "YOUR_GEMINI_API_KEY" # or set via LLM_API_KEY env var


[retrieval]
backend = "qdrant" # or "vertex"
qdrant_url = "https://YOUR-QDRANT-URL" # or set via QDRANT_URL env var
qdrant_api_key = "YOUR_QDRANT_KEY" # or set via QDRANT_API_KEY env var
collection = "trialwhisperer"


[data]
raw_dir = ".data/raw"
proc_dir = ".data/processed"


[data.api]
# ClinicalTrials.gov API base URL (defaults to https://www.clinicaltrials.gov/api/v2).
# Uncomment base_url to target an alternate host if the service moves again.
# base_url = "https://www.clinicaltrials.gov/api/v2"
backend = "requests" # HTTP client backend ("httpx" or "requests")
page_size = 100
max_studies = 200
# User-Agent defaults to TrialWhisperer/ingest (+https://trialwhisperer.ai/contact);
# override it with your own organization/contact string to represent your traffic.
user_agent = "my-app/1.0 (admin@example.com)"


[data.api.params]
"query.term" = "glioblastoma"
"filter.overallStatus" = ["RECRUITING", "ACTIVE_NOT_RECRUITING"]


[data.api.headers]
"X-Contact" = "admin@example.com"
