name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Google Cloud project ID'
        required: true
      region:
        description: 'Cloud Run region'
        required: false
        default: 'europe-west1'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: ${{ github.event.inputs.project_id }}
      REGION: ${{ github.event.inputs.region }}
      ENV_FILE: config/.env
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ github.event.inputs.project_id }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ github.event.inputs.project_id }}

      - name: Deploy to Cloud Run
        run: ./infra/deploy_cloudrun.sh
